### ISSUE TITLE
Editors on page stuck at 5px height and width.

### ISSUE THREAD

**Issue by cbj0** [serdarciplak/BlazorMonaco#36] opened 2021-03-09 14:08 UTC
![image](https://user-images.githubusercontent.com/43776825/110482811-05244180-8124-11eb-861b-44ea356e0a00.png)

**Comment by cbj0** [comment] 2021-03-09 14:10
HOW TO FIX THAT

**Comment by matt4446** [comment] 2021-03-12 12:45
I had the same issue and resolved it with some css which probably isn't the intended solution.
 
CSS for the razor component that BlazorMonaco sits on
```CSS
::deep .monaco-editor-container {
    height: 500px;
}
```

**Comment by serdarciplak** [comment] 2021-03-16 17:41
Duplicate of #24

**Closed by serdarciplak** 2021-03-16 17:41 UTC
