### ISSUE TITLE
Unable to bind value to c# object.

### ISSUE THREAD

**Issue by mpicca1** [serdarciplak/BlazorMonaco#107] opened 2023-09-25 13:02 UTC
Hello, how do I @bind-Value to this component? I want to link the data. Is there a way to data-bind the value to a string or a string property of an object?

**Comment by 35P10** [comment] 2023-11-29 03:25
Hi, try this:
```
<StandaloneCodeEditor @ref="_editor"  OnDidChangeModelContent="HandleInput">

@code
{
     private string code = "";
     private StandaloneCodeEditor _editor = null!;
     
     private async Task HandleInput(ModelContentChangedEvent e)
     {
          code = await _editor.GetValue();
     }
}
```
It works for me.

**Comment by serdarciplak** [comment] 2024-01-14 23:33
Duplicate of #55

**Closed by serdarciplak** 2024-01-14 23:33 UTC
