### ISSUE TITLE
Blazor server side

### ISSUE THREAD

**Issue by adiaz-iot** [serdarciplak/BlazorMonaco#34] opened 2021-03-04 11:32 UTC
Been trying to use it on a Blazor Server app and it seems to load fine but the component has no height, it shows as a very thin line. Is this something I'm missing or an incompatibility with Blazor Server?.
![blazormonaco_issue](https://user-images.githubusercontent.com/79848001/109957804-bd498880-7ce5-11eb-81de-cb59ca353c38.png)

**Comment by serdarciplak** [comment] 2021-03-16 17:41
Duplicate of #24

**Closed by serdarciplak** 2021-03-16 17:41 UTC
